services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: wahida
      POSTGRES_USER: wahida
      POSTGRES_PASSWORD: wahida
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infra/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf"]

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  judge0:
    image: judge0/judge0:1.13.1
    environment:
      - DISABLE_SANDBOX=false
      - JUDGE0_SERVER_NAME=wahida
    ports:
      - "2358:2358"

  celery:
    build:
      context: ./apps/api
    depends_on:
      - redis
      - postgres
    environment:
      - APP_NAME=Wahida API
      - BACKEND_CORS_ORIGINS=http://localhost:3000
      - POSTGRES_DSN=postgresql+psycopg://wahida:wahida@postgres:5432/wahida
      - REDIS_URL=redis://redis:6379/0
      - JUDGE0_URL=http://judge0:2358
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./apps/api:/app
      - ./content:/content:ro
      - ./data:/app/data
    command: ["celery", "-A", "app.tasks", "worker", "--loglevel=info"]

  api:
    build:
      context: ./apps/api
    depends_on:
      - postgres
      - redis
    environment:
      - APP_NAME=Wahida API
      - BACKEND_CORS_ORIGINS=http://localhost:3000
      - POSTGRES_DSN=postgresql+psycopg://wahida:wahida@postgres:5432/wahida
      - REDIS_URL=redis://redis:6379/0
      - JUDGE0_URL=http://judge0:2358
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./apps/api:/app
      - ./content:/content:ro
      - ./data:/app/data
    ports:
      - "8000:8000"

  web:
    build:
      context: ./apps/frontend
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - NEXT_PUBLIC_POSTHOG_KEY=${POSTHOG_API_KEY}
      - NEXT_PUBLIC_POSTHOG_HOST=https://app.posthog.com
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./apps/frontend:/app
      - ./content:/content:ro
    ports:
      - "3000:3000"

volumes:
  postgres-data:
