name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  backend:
    name: Backend - ruff, mypy, pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Ruff lint
        run: poetry run ruff check .
      - name: Mypy
        run: poetry run mypy app
      - name: Pytest
        run: poetry run pytest

  frontend:
    name: Frontend - pnpm lint & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build

  e2e:
    name: Playwright smoke
    needs: frontend
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    continue-on-error: true
    defaults:
      run:
        working-directory: apps/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Run smoke tests
        run: pnpm test:e2e
